--- 
abstract: Version-agnostic storage and manipulation of SQLite databases
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: SQLite-Archive
no_index: 
  directory: 
    - inc
    - t
requires: 
  Archive::Extract: 0.22
  Carp: 0
  DBD::SQLite: 1.09
  DBI: 1.53
  File::Spec: 0.80
  File::Temp: 0
  IO::Zlib: 1.05
  Parse::CSV: 1.00
  SQL::Script: 0.03
  perl: 5.005
version: 0.01
